FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm i

COPY . .
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./
COPY .env .env

RUN npm i --omit=dev

CMD ["npm", "start"]
